---
- name: clone the cgminer repository
  git: repo=https://github.com/ckolivas/cgminer dest=/opt/cgminer

- name: install dependencies
  apt: name={{item}} state=present
  with_items:
    - build-essential
    - autoconf
    - automake
    - libtool
    - pkg-config
    - libcurl3-dev
    - libudev-dev
    - usbutils

- name: build cgminer
  shell: |
    cd /opt/cgminer && \
    cp 01-cgminer.rules /etc/udev/rules.d/ && \
    echo /usr/local/lib > /etc/ld.so.conf.d/usrlocal.conf && \
    ./autogen.sh && \
    opts="--enable-avalon --enable-hashfast --enable-icarus" && \
    CFLAGS="-O2 -Wall -march=native" ./configure $opts && \
    make

- name: send the script into /usr/local/bin
  copy:
    src="cgminer"
    dest="/usr/local/bin/cgminer"
    mode=0755

- name: run service with tmux help
  command: /usr/local/bin/cgminer
