---
- name: clone the cgminer repository
  git: repo=https://github.com/ckolivas/cgminer.git dest=/opt/cgminer

- name: install dependencies
  apt: name={{item}} state=present
  with_items:
    - build-essential
    - autoconf
    - automake
    - libtool
    - pkg-config
    - libcurl3-dev
    - libudev-dev
    - usbutils

- name: build cgminer
  shell: |
    cd /opt/cgminer && \
    cp 01-cgminer.rules /etc/udev/rules.d/ && \
    echo '/usr/local/lib' > /etc/ld.so.conf.d/usrlocal.conf && \
    modprobe pl2303   vendor=0x067b product=0x0230 && \ # modprobe icarus devices
    ./autogen.sh && \
    CFLAGS="-O2 -Wall -march=native" ./configure --enable-avalon --enable-hashfast --enable-icarus && \
    make && make install

- name: send the script into /usr/local/bin
  copy:
    src="cgminer"
    dest="/usr/local/bin/cgminerd"
    mode=0755

- name: ensure .cgminer dir on root
  file: path="/root/.cgminer" owner=root state=directory mode=0755

- name: send the config file
  copy: src=cgminer.conf dest={{item}}
  with_items:
    - /root/.cgminer/cgminer.conf
    - /etc/cgminer.conf

- name: run service with tmux help
  command: /usr/local/bin/cgminerd
