---
- hosts: all
  remote_user: pi
  sudo: yes
  pre_tasks:
    - name: Load variables
      include_vars: vars.yml
      nocows: True
  roles:
    - common
    - server
    - media
  # post_tasks:
  #   - name: Reboot
  #     command: /sbin/reboot
