- name: dnsmasq | install
  apt: name=dnsmasq state=present

- name: dnsmasq | configure 
  template: src=dnsmasq.conf dest=/etc/dnsmasq.conf

- name: dnsmasq | running
  service: name=dnsmasq state=running
