- name: dnsmasq | install
  apt: name=dnsmasq state=present

- name: dnsmasq | configure
  template: src=dnsmasq.conf dest=/etc/dnsmasq.conf

- name: dnsmasq | running
  service: name=dnsmasq state=running

- name: nfs
  apt: name={{ item }} state=present
  with_items:
    - nfs-common
    - nfs-server

- name: nfs conf
  template:
    src=nfs.conf
    dest=/etc/exports
    owner=root
    mode=0766

- name: trigger exports file for nfs
  command: exportfs

- name: enable rpcbind
  command: update-rc.d rpcbind enable

- name: rpcbind | running
  service: name=rpcbind state=running
