---
- name: Update apt package cache
  apt: update_cache=yes cache_valid_time=72000

- name: Install common packages
  apt: name={{item}} state=present
  with_items:
    - curl
    - htop
    - vim
    - git
    - tmux
    - ruby
    - python
    - wpasupplicant

- name: Setting up a better hosts file
  get_url: url=http://someonewhocares.org/hosts/hosts
           dest=/etc/hosts
           mode=0644
           owner=root
           group=root
           force=yes

- name: Ensure wifi config path exists
  file: path=/etc/wpa_supplicant state=directory

- name: Configure wifi
  template: src=wpa_supplicant/wpa_supplicant.conf
            dest=/etc/wpa_supplicant/wpa_supplicant.conf
            mode=0644
            owner=root
            group=root

- name: Get customized dotfiles
  git: repo=https://github.com/mvrilo/dotfiles
       dest=/tmp/dotfiles
       recursive=yes

- name: Ensure that tmux plugin dir exists in skel
  file: path={{item}}/.tmux/plugins/tpm state=directory
  with_items:
    - /etc/skel
    - "{{ ansible_env.HOME }}"

- name: Set customized dotfiles to users
  shell: cp -a /tmp/dotfiles/. {{item}}
  with_items:
    - /etc/skel
    - "{{ ansible_env.HOME }}"

- name: Copy unblockus script
  copy: src=unblockus dest=/usr/local/bin/ mode=0775

- name: Sets the unblockus script on cron
  cron:
    name="check ip availability of unblockus"
    cron_file="unblockus-hourly-2"
    job="/usr/local/bin/unblockus"
    user="root"
    minute="0"
    hour="*/2"
