---
- name: sets the hostname
  hostname: name={{ HOSTNAME | default("box") }}

- name: Get the host part of the IP 
  shell: hostname --all-ip-address
  register: host_ip 

- debug: var=host_ip

- name: update apt cache
  apt: update_cache=yes cache_valid_time=86400

- name: install common packages
  apt: name={{item}} state=present
  with_items:
    - vim
    - git
    - tree
    - tmux
    - ruby
    - curl
    - htop
    - nmap
    - unzip
    - openssl
    - automake
    - libssl-dev
    - python
    - python-dev
    - python-pip
    - python3-lxml
    - python-software-properties
    - software-properties-common
    - build-essential
    - dnsutils

- name: vim forever!
  lineinfile: dest=/etc/bash.bashrc line='export EDITOR=$(which vim)' owner=root group=root

- name: setting up ad-blocking hosts
  copy:
    src=hosts.gz
    dest=/tmp/hosts.gz
    owner=root
    mode=0644

- shell: gunzip /tmp/hosts.gz; mv /tmp/hosts /etc/hosts

- name: add hostname in hosts
  when: HOSTNAME is defined
  lineinfile:
    dest=/etc/hosts
    insertbefore=BOF
    line="127.0.0.1 {{ HOSTNAME | default('box.pi') }}"

- name: add hostname in hosts
  when: HOSTNAME is defined
  lineinfile:
    dest=/etc/hosts
    insertbefore=BOF
    line="{{ host_ip.stdout }} {{ HOSTNAME | default('box.pi') }}"

- name: copy unblockus script
  copy: src=unblockus dest=/usr/local/bin/ mode=0775

- name: set the unblockus script on cron
  when: EMAIL is defined
  cron:
    name="check ip availability of unblockus"
    cron_file="unblockus-hourly-2"
    job="/usr/local/bin/unblockus {{ EMAIL }}"
    user="root"
    minute="0"
    hour="*/2"
