---
- name: set hostname
  hostname: name={{hostname}}

- name: add jessie repo
  lineinfile: dest=/etc/apt/sources.list line="deb http://httpredir.debian.org/debian jessie main\ndeb-src http://httpredir.debian.org/debian jessie main\ndeb http://security.debian.org/ jessie/updates main\ndeb-src http://security.debian.org/ jessie/updates main"

- name: add jessie repo pref
  copy: src=jessie.pref dest=/etc/apt/preferences.d/jessie.pref

- name: update apt cache
  apt: update_cache=yes

- name: install common packages
  apt: name={{item}} state=present
  with_items:
    - vim
    - git
    - tree
    - tmux
    - ruby
    - curl
    - htop
    - openssl
    - python
    - python-dev
    - python-pip
    - python3-lxml
    - python-software-properties
    - wpasupplicant
    - software-properties-common
    - libffi-dev

- name: vim forever
  lineinfile: dest=/etc/bash.bashrc line='export EDITOR=$(which vim)' owner=root group=root

- name: setting up ad-blocking hosts
  get_url: url=http://someonewhocares.org/hosts/hosts
           dest=/etc/hosts
           mode=0644
           owner=root
           group=root
           force=yes

- name: setting up hostname in hosts
  lineinfile: dest=/etc/hosts regexp='127.0.0.1\tlocalhost$' line='127.0.0.1\tlocalhost\t{{hostname}}'

- name: ensure wifi config path exists
  file: path=/etc/wpa_supplicant state=directory

- name: config wifi
  template: src=wpa_supplicant/wpa_supplicant.conf
            dest=/etc/wpa_supplicant/wpa_supplicant.conf
            mode=0644
            owner=root
            group=root

- name: download dotfiles
  git: repo=https://github.com/mvrilo/dotfiles
       dest=/tmp/dotfiles
       recursive=yes

- name: ensure tmux plugin dir existance
  file: path={{item}}/.tmux/plugins/tpm state=directory
  with_items:
    - /etc/skel
    - "{{ ansible_env.HOME }}"

- name: set customized dotfiles to users
  shell: cp -a /tmp/dotfiles/. {{item}}
  with_items:
    - /etc/skel
    - "{{ ansible_env.HOME }}"

- name: copy unblockus script
  copy: src=unblockus dest=/usr/local/bin/ mode=0775

- name: set the unblockus script on cron
  cron:
    name="check ip availability of unblockus"
    cron_file="unblockus-hourly-2"
    job="/usr/local/bin/unblockus"
    user="root"
    minute="0"
    hour="*/2"
