---
- name: add dirs
  file: path={{item}} state=directory mode=0777
  with_items:
    - "{{watch}}"
    - "{{downloads}}"
    - "{{incomplete}}"
    - "{{media}}"
    - "{{media}}/Music"
    - "{{media}}/Movies"
    - "{{media}}/TVShows"

- name: download subliminal
  easy_install: name=subliminal executable=yes

- name: subtitles download script
  template: src=subs dest=/usr/local/bin/ mode=0775

- include: transmission.yml
- include: couchpotato.yml
- include: sickrage.yml
