---
- name: add dirs
  file: path="{{ HDD }}{{item}}" state=directory mode=0777
  with_items:
    - "/"
    - "/.watch"
    - "/.downloads"
    - "/.incomplete"
    - "/Music"
    - "/Movies"
    - "/TVShows"

- name: download subliminal
  easy_install: name=subliminal

- name: subtitles download script
  when: EMAIL is defined
  template: src=subs dest=/usr/local/bin/ mode=0775

- include: transmission.yml
- include: couchpotato.yml
- include: sickrage.yml
