---
- name: Add Media dir
  file: path={{media}} state=directory mode=0777

- name: Get subliminal
  easy_install: name=subliminal executable=yes

- name: Script to automatic download subtitles
  template: src=subs dest=/usr/local/bin/ mode=0775

- include: transmission.yml
