---
- name: transmission | install daemon
  apt: name={{item}} default_release=jessie state=present
  with_items:
    - transmission-daemon
    - transmission-cli

- name: transmission | stop
  service: name=transmission-daemon state=stopped

- name: transmission | copy config file
  template:
    src=transmission.json
    dest=/etc/transmission-daemon/settings.json
    owner=debian-transmission
    mode=0766

- name: transmission | start
  service: name=transmission-daemon state=started
