---
- name: transmission | add apt repository
  apt_repository: repo="ppa:transmissionbt/ppa"
  ignore_errors: yes # will fail on debian

- name: transmission | install daemon
  apt: name={{item}} state=present
  with_items:
    - transmission-daemon
    - transmission-cli

- name: transmission | stop
  service: name=transmission-daemon state=stopped

- name: transmission | copy config file
  template:
    src=transmission.json
    dest=/etc/transmission-daemon/settings.json
    owner=debian-transmission
    mode=0766

- name: transmission | start
  service: name=transmission-daemon state=started
