---
- name: Add transmission APT repository
  apt_repository: repo="ppa:transmissionbt/ppa"

- name: Install transmission daemon
  apt: name={{item}} state=present
  with_items:
    - transmission-daemon
    - transmission-cli

- name: Stop transmission
  service: name=transmission-daemon state=stopped

- name: Add downloads dir
  file: path={{downloads}} owner=debian-transmission state=directory mode=0777

- name: Add downloads dir
  file: path={{downloads}} owner=debian-transmission state=directory mode=0777

- name: Add watch dir
  file: path={{watch}} owner=debian-transmission state=directory

- name: Copy Transmission configuration
  template:
    src=transmission.json
    dest=/etc/transmission-daemon/settings.json
    owner=debian-transmission
    mode=0766

- name: Start transmission
  service: name=transmission-daemon state=started
