media: /media/media
downloads: /media/downloads
incomplete: /media/incomplete
watch: /media/watch
subs: /usr/bin/subs
pushbullet_token: ""

transmission:
  address: 0.0.0.0
  port: 9091
  user: transmission
  password: ""
  ratio: 5

couchpotato:
  user: ""
  password: ""
  address: 0.0.0.0
  port: 5050
  imdb:
    watchlist_url: ""

sickrage:
  user: ""
  password: ""
  address: 0.0.0.0
  port: 8085
